import blobshape from "blobshape";

/**
 * The soft shapes behind the affirmation.
 *
 * Two rules govern everything here, and both are about restraint:
 *
 *   1. The artwork must never compete with the words. Shapes are large, soft,
 *      low-opacity, and pushed toward the edges — the middle of the screen is
 *      left alone, because that is where the affirmation is.
 *   2. Every colour comes from the active theme. Hardcoding a hue is how a coral
 *      shape ends up glowing behind a sage backdrop.
 *
 * Shapes are generated by `blobshape` from a seed derived from the theme slug,
 * so a theme looks the same every launch — a backdrop that reshuffles itself on
 * every open is a different app each morning, which is the opposite of what a
 * daily ritual wants.
 *
 * Compositions differ per theme rather than being one layout recoloured, so
 * switching theme is a change of scene and not a change of tint.
 */

// Positions and sizes are fractions of the screen, so the composition holds on a
// small phone and a tablet alike.
const COMPOSITIONS = {
  // Warm and enveloping: two large washes that meet behind the words, a soft
  // rose accent low-left, and two small highlights so the field has some life
  // in it rather than reading as one flat smudge.
  dawn: [
    { x: -0.34, y: -0.16, size: 1.15, edges: 6, growth: 6, color: "accentSoft", opacity: 0.3 },
    { x: 0.42, y: 0.5, size: 1.2, edges: 5, growth: 7, color: "accent", opacity: 0.2 },
    { x: -0.18, y: 0.66, size: 0.8, edges: 7, growth: 8, color: "border", opacity: 0.26 },
    { x: 0.66, y: -0.06, size: 0.42, edges: 8, growth: 5, color: "border", opacity: 0.24 },
    { x: 0.1, y: 0.28, size: 0.55, edges: 6, growth: 9, color: "accentSoft", opacity: 0.16 },
  ],
  blush: [
    { x: -0.36, y: 0.02, size: 1.25, edges: 5, growth: 7, color: "accentSoft", opacity: 0.28 },
    { x: 0.4, y: 0.5, size: 1.05, edges: 6, growth: 6, color: "border", opacity: 0.3 },
    { x: 0.24, y: -0.26, size: 0.85, edges: 7, growth: 8, color: "accent", opacity: 0.16 },
    { x: -0.12, y: 0.72, size: 0.6, edges: 6, growth: 7, color: "accentSoft", opacity: 0.22 },
  ],
  // Fewer edges and more growth read as leaf-like rather than bubble-like.
  sage: [
    { x: -0.26, y: 0.54, size: 1.1, edges: 4, growth: 8, color: "accent", opacity: 0.22 },
    { x: 0.44, y: -0.18, size: 1.05, edges: 4, growth: 9, color: "accentSoft", opacity: 0.28 },
    { x: 0.6, y: 0.7, size: 0.6, edges: 5, growth: 7, color: "border", opacity: 0.3 },
    { x: -0.08, y: 0.02, size: 0.5, edges: 6, growth: 8, color: "accentSoft", opacity: 0.18 },
  ],
  // Wide and low: a horizon rather than a cluster.
  sky: [
    { x: -0.4, y: 0.6, size: 1.5, edges: 8, growth: 9, color: "accentSoft", opacity: 0.26 },
    { x: 0.24, y: -0.3, size: 1.25, edges: 8, growth: 8, color: "border", opacity: 0.3 },
    { x: 0.68, y: 0.3, size: 0.42, edges: 6, growth: 6, color: "accent", opacity: 0.18 },
    { x: -0.1, y: 0.18, size: 0.5, edges: 7, growth: 9, color: "accentSoft", opacity: 0.14 },
  ],
  // Dark themes take a lower opacity: the same value reads far brighter against
  // a dark backdrop, and a glow that outshines the type defeats the point.
  dusk: [
    { x: -0.32, y: -0.1, size: 1.2, edges: 5, growth: 8, color: "accent", opacity: 0.16 },
    { x: 0.42, y: 0.52, size: 1.1, edges: 6, growth: 7, color: "accentSoft", opacity: 0.13 },
    { x: 0.6, y: 0.02, size: 0.45, edges: 7, growth: 6, color: "border", opacity: 0.16 },
  ],
  midnight: [
    { x: -0.26, y: 0.56, size: 1.25, edges: 6, growth: 8, color: "accent", opacity: 0.14 },
    { x: 0.38, y: -0.22, size: 1.1, edges: 7, growth: 7, color: "accentSoft", opacity: 0.12 },
    { x: 0.72, y: 0.28, size: 0.36, edges: 8, growth: 6, color: "border", opacity: 0.18 },
  ],
};

const FALLBACK = COMPOSITIONS.dawn;

// Slow enough to be felt rather than watched. A backdrop that visibly moves is
// something to look at; this should only ever be something to look past.
const DRIFT_MS = [15000, 19000, 23000, 17000, 21000];
const DRIFT_PX = [14, 10, 18, 12, 16];

/**
 * Turns a theme into positioned, coloured shapes for a given screen size.
 *
 * Pure: no rendering, no animation, no randomness — the same theme and size
 * always produce the same composition, which is what makes it testable and what
 * keeps a theme looking like itself.
 */
export function buildArtwork(theme, { width, height }) {
  const composition = COMPOSITIONS[theme?.slug] ?? FALLBACK;
  const base = Math.max(width, height);

  return composition.map((shape, index) => {
    const size = Math.round(base * shape.size);

    return {
      key: `${theme?.slug ?? "default"}-${index}`,
      // blobshape works in its own coordinate space; the SVG viewBox scales it.
      path: blobshape({
        size: 100,
        growth: shape.growth,
        edges: shape.edges,
        seed: `${theme?.slug ?? "default"}-${index}`,
      }).path,
      size,
      left: Math.round(width * shape.x),
      top: Math.round(height * shape.y),
      color: theme?.[shape.color] ?? theme?.accent ?? "#FF6F61",
      opacity: shape.opacity,
      duration: DRIFT_MS[index % DRIFT_MS.length],
      distance: DRIFT_PX[index % DRIFT_PX.length],
    };
  });
}

/**
 * Which way the blur pass should lean.
 *
 * A light blur over a midnight backdrop washes it grey, which is the one thing
 * a dark theme must not do — so this follows the theme rather than the system
 * appearance.
 */
export const blurTintFor = (theme) => (theme?.dark ? "dark" : "light");

/** Exposed so a test can assert every theme has a composition of its own. */
export const ARTWORK_SLUGS = Object.keys(COMPOSITIONS);
